version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    networks:
      - app-network
  
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: .env
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file: .env
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:

volumes:
  notebook-data:
  postgres-data: